name: ci
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  eslint:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Install
        uses: ./.github/workflow/composite/install
      - name: Eslint
        run: pnpm run eslint-check
